<?php
return [
    'tours' => [
        [
            'duration' => '7 days',
            'image' => 'https://www.viaggi-usa.it/wp-content/uploads/2017/07/copertina-e1637224925993.jpg',
            'location' => 'Hawaai',
            'date_start' => '2020/06/20',
            'date_return' => '2020/06/27',
            'is_avaible' => true,
            'number_posts_avaible' => 15,
            'type_tour' => 'Crociera',
            'price' => 600,
            'services' => 'Wi-Fi nella hall,
            Wi-Fi gratis,
            Piscina,
            Spa,
            Parcheggio,
            Animali ammessi,
            A/C,
            Ristorante,
            Bar dell\'hotel,
            Palestra',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt, voluptates amet ipsa nihil explicabo quos repellendus, repudiandae sequi.'
        ],
        [
            'duration' => '10 days',
            'image' => 'https://e291f1206726d700191b-d0cedd1cc05016668dc83bc2742129e5.ssl.cf1.rackcdn.com/windsong/media/windsong-mega-resorts-hero-5f5297b9c9e02.jpg',
            'location' => 'Bahamas',
            'date_start' => '2020/06/30',
            'date_return' => '2020/07/10',
            'is_avaible' => true,
            'number_posts_avaible' => 5,
            'type_tour' => 'Hotel',
            'price' => 850,
            'services' =>
            'Wi-Fi nella hall,
            Wi-Fi gratis,
            Piscina,
            Spa,
            Parcheggio,
            Animali ammessi,
            A/C,
            Ristorante,
            Bar dell\'hotel,
            Palestra,
            Pensione Completa,
            Cassaforte in hotel,
            Disinfezione costante,
            Facchino,
            PC con internet,
            Pagamento senza contanti,
            Reception 24 ore su 24,
            Sala riunioni,
            Servizio di concierge,
            Servizio di lavanderia,
            Servizio in camera,
            Servizio navetta',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt, voluptates amet ipsa nihil explicabo quos repellendus, repudiandae sequi.'
        ],
        [
            'duration' => '3 days',
            'image' => 'https://www.doveclub.it/wp-content/uploads/2020/10/aurora.jpg',
            'location' => 'Norvegia (Fiordi)',
            'date_start' => '2020/08/15',
            'date_return' => '2020/08/18',
            'is_avaible' => true,
            'number_posts_avaible' => 25,
            'type_tour' => 'Tour Guidato + Hotel + Volo',
            'price' => 600,
            'services' =>
            'Wi-Fi gratis,
            Animali ammessi,
            A/C,
            Ristorante,
            Bar dell\'hotel,
            Palestra',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt, voluptates amet ipsa nihil explicabo quos repellendus, repudiandae sequi.'
        ],
        [
            'duration' => '5 days',
            'image' => 'https://cdn.getyourguide.com/img/location/5ffeb0b587f00.jpeg/99.jpg',
            'location' => 'Amsterdam',
            'date_start' => '2020/05/10',
            'date_return' => '2020/05/15',
            'is_avaible' => true,
            'number_posts_avaible' => 15,
            'type_tour' => 'Hotel',
            'price' => 300,
            'services' =>
            'Wi-Fi nella hall,
            Wi-Fi gratis,
            Piscina,
            Spa,
            Parcheggio,
            Animali ammessi,
            A/C,
            Ristorante,
            Bar dell\'hotel,
            Palestra,
            Pensione Completa,
            Cassaforte in hotel,
            Disinfezione costante,
            Facchino',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt, voluptates amet ipsa nihil explicabo quos repellendus, repudiandae sequi.'
        ],
        [
            'duration' => '15 days',
            'image' => 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/29/95/29959_v2.jpeg',
            'location' => 'Santo Domingo',
            'date_start' => '2020/06/12',
            'date_return' => '2020/06/27',
            'is_avaible' => true,
            'number_posts_avaible' => 10,
            'type_tour' => 'Volo + Hotel',
            'price' => 1200,
            'services' =>
            'Wi-Fi nella hall,
            Wi-Fi gratis,
            Piscina,
            Spa,
            Parcheggio,
            Animali ammessi,
            A/C,
            Ristorante,
            Bar dell\hotel,
            Palestra,
            Pensione Completa,
            Cassaforte in hotel,
            Disinfezione costante,
            Facchino,
            PC con internet,
            Pagamento senza contanti,
            Reception 24 ore su 24,
            Sala riunioni,
            Servizio di concierge,
            Servizio di lavanderia,
            Servizio in camera,
            Servizio navetta',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt, voluptates amet ipsa nihil explicabo quos repellendus, repudiandae sequi.'
        ],
        [
            'duration' => '1 days',
            'image' => 'https://www.berlino.com/wp-content/uploads/sites/13/Berlino-Cosa-Vedere-thumbnail.jpg',
            'location' => 'Berlino',
            'date_start' => '2020/06/20',
            'date_return' => '2020/06/21',
            'is_avaible' => true,
            'number_posts_avaible' => 5,
            'type_tour' => 'Tour della Città',
            'price' => 100,
            'services' => 'Servizio Navetta',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt, voluptates amet ipsa nihil explicabo quos repellendus, repudiandae sequi.'
        ]
    ]
];
